collections:
  projects:
    order:
      - anomalies.md
      - souschef.md
      - easydraft.md
      - ner-annotation-helper.md

excerpt_separator: <!--more-->

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
